spring:
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true

  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: none
    show-sql: false
    hibernate.jdbc.time_zone: UTC

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_service?currentSchema=user_service
    username: postgres
    password: zaq12wsx